// Keeps already-open editor tabs in sync with filesystem watcher events.
// Binary viewer tabs need a remount so their byte-loading effects re-run; clean
// text tabs can be safely replaced with fresh disk content.

import { flushPendingEdits, isTextDoc, useEditorStore } from "../state/editorStore";
import { readFile } from "./ipc";

function normalizePath(path: string): string {
  return path.replace(/\\/g, "/");
}

export async function reloadOpenEditorPaths(paths: string[]): Promise<void> {
  if (paths.length === 0) return;

  // Commit any debounced editor->store write first: a just-edited doc must not
  // look clean here and get its in-memory edits overwritten with disk content.
  flushPendingEdits();
  const changed = new Set(paths.map(normalizePath));
  const docs = useEditorStore
    .getState()
    .docs.filter((doc) => changed.has(normalizePath(doc.path)));

  for (const doc of docs) {
    if (doc.kind === "pdf" || doc.kind === "image") {
      useEditorStore.getState().bumpReloadVersion(doc.path);
      continue;
    }

    if (!isTextDoc(doc) || doc.content !== doc.savedContent) continue;
    void reloadCleanTextDoc(doc.path);
  }
}

// Per-path read serialization. Two separate watcher batches can fire a read for
// the SAME path before the first resolves; if an older read's apply advances
// savedContent, the save-during-read guard in replaceCleanContentFromDisk would
// then reject the second (newer) read's bytes and leave the editor stale vs disk.
// Chaining per path makes each read observe the previous read's applied state, so
// the newest disk bytes always win. The common no-overlap case runs applyDiskRead
// synchronously, so a single reload adds no extra latency or microtask hops.
const inFlightReads = new Map<string, Promise<void>>();

function reloadCleanTextDoc(path: string): Promise<void> {
  const prev = inFlightReads.get(path);
  const next = prev ? prev.then(() => applyDiskRead(path)) : applyDiskRead(path);
  inFlightReads.set(path, next);
  void next.finally(() => {
    if (inFlightReads.get(path) === next) inFlightReads.delete(path);
  });
  return next;
}

async function applyDiskRead(path: string): Promise<void> {
  // Re-read live state: a previous chained read (or an in-editor edit) may have
  // changed the doc since this read was enqueued.
  const doc = useEditorStore.getState().docs.find((d) => d.path === path);
  if (!doc || !isTextDoc(doc) || doc.content !== doc.savedContent) return;
  // Capture savedContent BEFORE the async read. If the user saves new content
  // during the read's IPC round-trip, savedContent changes and the store action
  // skips the overwrite, so stale disk bytes can't clobber a just-saved buffer.
  const expectedSavedContent = doc.savedContent;

  try {
    const content = await readFile(path);
    useEditorStore
      .getState()
      .replaceCleanContentFromDisk(path, content, expectedSavedContent);
  } catch {
    // The path may have been deleted/renamed between the watcher event and the
    // read, or the read was refused by the backend's file-size cap (a large open
    // file regenerated by a build would otherwise error on every debounced
    // event). Keep the open tab stable and stay quiet — logging would spam the
    // console for repeatedly-touched files.
  }
}
