// Keeps already-open editor tabs in sync with filesystem watcher events.
// Binary viewer tabs need a remount so their byte-loading effects re-run; clean
// text tabs can be safely replaced with fresh disk content.

import { flushPendingEdits, isTextDoc, useEditorStore } from "../state/editorStore";
import { readFile } from "./ipc";

function normalizePath(path: string): string {
  return path.replace(/\\/g, "/");
}

export async function reloadOpenEditorPaths(paths: string[]): Promise<void> {
  if (paths.length === 0) return;

  // Commit any debounced editor->store write first: a just-edited doc must not
  // look clean here and get its in-memory edits overwritten with disk content.
  flushPendingEdits();
  const changed = new Set(paths.map(normalizePath));
  const docs = useEditorStore
    .getState()
    .docs.filter((doc) => changed.has(normalizePath(doc.path)));

  for (const doc of docs) {
    if (doc.kind === "pdf" || doc.kind === "image") {
      useEditorStore.getState().bumpReloadVersion(doc.path);
      continue;
    }

    if (!isTextDoc(doc) || doc.content !== doc.savedContent) continue;
    // Capture savedContent BEFORE the async read. If the user saves new content
    // during the read's IPC round-trip, the doc's savedContent changes; the
    // store action below sees the mismatch and skips the overwrite, so stale
    // disk bytes can never clobber a just-saved buffer (and its undo stack).
    const expectedSavedContent = doc.savedContent;

    try {
      const content = await readFile(doc.path);
      useEditorStore
        .getState()
        .replaceCleanContentFromDisk(doc.path, content, expectedSavedContent);
    } catch {
      // The path may have been deleted/renamed between the watcher event and
      // the read, or the read was refused by the backend's file-size cap (a
      // large open file regenerated by a build would otherwise error on every
      // debounced watcher event). Keep the open tab stable and stay quiet —
      // logging here would spam the console for repeatedly-touched files.
    }
  }
}
